name: "Colorize CDK diff output"
description: "Colorize CDK diff output"
inputs:
  cdk-diff-output:
    description: "CDK diff output"
    required: true
  python-version:
    description: “Python version”
    required: true
    default: "3.12"
runs:
  using: "composite" 
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - name: Cdk diff
      shell: bash
      run: |
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          echo "${{inputs.cdk-diff-output}}" | python $GITHUB_ACTION_PATH/colorize.py >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          OUTPUT=$(cat $GITHUB_STEP_SUMMARY)
          echo "CDK_DIFF_RESULT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
    - name: Insert cdk diff output as comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        header: diff_result
        message: |
          ${{ env.CDK_DIFF_RESULT }}