linters:
  enable:
    - gci
    - godot
    - gofmt
    - misspell
    - revive
    - whitespace
    - gosec
linters-settings:
  gci:
    sections:
      - standard
      - default
    custom-order: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - text: "G104: Errors unhandled."
      linters:
        - gosec
run:
  timeout: 10m